### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by georgievayo** [The-Feigned-Panthers/bookAtable#1]
1. User component: login, logout, sign up, profile, make a booking, amend a booking, cancel a booking, leave a review(only if he has already visited a place), share on social channels, rate place
2. Owner component: login, logout, sign up, add new place, update place, delete place
3. Places component: show all, newest, most popular places, search by criteria, show details of place(+reviews)

**Comment by Didexe** [comment]
user.auth was commented out in the component constructor
